templates:
  collection:
    default:
      collection_order: release
      minimum_items: 2
    optional:
      - collection
      - movie
      - name_mapping
      - sort_title
      - build_collection
      - item_label
      - summary
      - collection_mode
    cache_builders: 1
    minimum_items: <<minimum_items>>
    tmdb_collection_details: <<value>>
    tmdb_movie: <<movie>>
    name_mapping: <<name_mapping>>
    sort_title: <<sort_title>>
    build_collection: <<build_collection>>
    sync_mode: sync
    collection_order: <<collection_order>>
    collection_mode: <<collection_mode>>
    item_label: <<item_label>>
    summary: <<summary>>
